INSERT INTO LOCATIONS (NAME,TYPE,LAT,LNG)
VALUES ('BRISTOL PUBLIC HOSPITAL', 'NHS', 51.47, -2.59 );

INSERT INTO LOCATIONS (NAME,TYPE,LAT,LNG)
VALUES ('Ospedale Italiano', 'Private', 51.45, -2.55 );

INSERT INTO LOCATIONS (NAME,TYPE,LAT,LNG)
VALUES ('Uni Hospital', 'Private', 51.49, -2.52 );

INSERT INTO LOCATIONS (NAME,TYPE,LAT,LNG)
VALUES ('Longwell gp', 'Private', 51.43, -2.48 );

INSERT INTO LOCATIONS (NAME,TYPE,LAT,LNG)
VALUES ('Nailsea Hospital', 'NHS', 51.42, -2.73 );

