CREATE TABLE Locations (
    locationID INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
    Name VARCHAR(50),
    Type VARCHAR(50),
    Lat FLOAT,
    Lng FLOAT
)