create table "SMARTCARE".USERS
(
	USERNAME VARCHAR(35) not null primary key,
	FIRSTNAME VARCHAR(30) not null,
	LASTNAME VARCHAR(30) not null,
	USERTYPE VARCHAR(1) not null,
	DOB DATE,
	REGDATE DATE,
	PHONE VARCHAR(11),
	EMAIL VARCHAR(64),
	ADDRESS VARCHAR(70),
	PASSWORD VARCHAR(60) not null,
	TITLE VARCHAR(10)
)